2019-08-08 10:01:37,788 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 10:01:49,188 ERROR: Exception on /login [POST] [in c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lenovo_owner\microblog\venv\app\routes.py", line 42, in login
    return redirect(url_for('loginn'))
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'loginn'. Did you mean 'login' instead?
2019-08-08 10:03:29,882 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 10:40:49,271 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 10:41:11,236 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 11:11:19,607 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 11:11:50,232 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 11:14:13,311 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 12:44:08,475 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 12:46:14,629 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 12:56:40,788 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:06:45,230 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:06:54,261 ERROR: Exception on /user/Shivam [GET] [in c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\users\lenovo_owner\microblog\venv\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo_owner\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\users\lenovo_owner\microblog\venv\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\lenovo_owner\microblog\venv\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "c:\users\lenovo_owner\microblog\venv\app\templates\user.html", line 6, in block "content"
    <td><img src="{{ user.avatar(128) }}"></td>
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
2019-08-08 13:09:15,291 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:09:20,432 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:09:57,581 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:10:43,046 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:13:03,739 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:16:47,217 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:17:07,395 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:23:10,014 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
2019-08-08 13:27:21,543 INFO: Microblog startup [in c:\users\lenovo_owner\microblog\venv\app\__init__.py:46]
